# Generated by Django 4.0.4 on 2022-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.TextField(unique=True)),
                ('transaction', models.BinaryField()),
                ('block_type', models.TextField()),
                ('previous_hash', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
