# Generated by Django 4.0.4 on 2022-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidia', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privatekey',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
