# Generated by Django 4.0.4 on 2022-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidia', '0005_alter_user_privatekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditrequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('fileid', models.IntegerField()),
                ('tpastatus', models.IntegerField(default=0)),
                ('tpaat', models.DateTimeField()),
                ('cloudstatus', models.IntegerField(default=0)),
                ('cloudauditat', models.DateTimeField()),
                ('cloudhashresult', models.TextField()),
                ('tpaverification', models.IntegerField(default=0)),
                ('tpaverifiedat', models.DateTimeField()),
                ('userverification', models.IntegerField(default=0)),
                ('userverifiedat', models.DateTimeField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fileuploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('filename', models.CharField(max_length=200)),
                ('hashcode', models.TextField()),
                ('cloudname', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
