# Generated by Django 4.0.4 on 2022-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidia', '0006_auditrequest_fileuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='key',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
