# Generated by Django 4.0.4 on 2022-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidia', '0007_fileuploads_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrequest',
            name='cloudauditat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='cloudhashresult',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='tpaat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='tpaverifiedat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auditrequest',
            name='userverifiedat',
            field=models.DateTimeField(null=True),
        ),
    ]
