# Generated by Django 4.0.4 on 2022-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidia', '0009_rename_tap_tpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='key',
            field=models.BinaryField(),
        ),
    ]
